function createfigure(yvector1)
%CREATEFIGURE(yvector1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 25-Sep-2024 12:35:24

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
bar(yvector1,'FaceColor',[0.2 0.6 0.8]);

% Create ylabel
ylabel('Massenstrom [kg/s]');

% Create xlabel
xlabel('Komponenten');

% Create title
title('Massenströme des Raketentriebwerks');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',12,'XTick',[1 2 3],'XTickLabel',...
    {'Treibstoff','Oxidationsmittel','Gesamt'});
